# Generated by Django 6.0.4 on 2026-06-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('autor_id', models.PositiveIntegerField()),
                ('autor_nombre', models.CharField(max_length=100)),
                ('autor_email', models.EmailField(max_length=254)),
                ('entidad_id', models.PositiveIntegerField()),
                ('entidad_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('editado_por_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('editado_por_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('editado_por_fecha', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
